version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php-apache
    ports:
      - '8080:80'
    volumes:
      - ./Library:/var/www/html/
      - ./99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9003

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Library'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./Library/db/Library.sql:/docker-entrypoint-initdb.d/Library.sql
# Names our volume
volumes:
  my-db: