FROM php:8.1.2-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN pecl install xdebug && docker-php-ext-enable xdebug

WORKDIR /var/www/html
RUN adduser --disabled-password --gecos '' developer
USER developer

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:8080/ || exit 1

EXPOSE 8080